language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

install:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

notifications:
    irc: "irc.freenode.org#noiselabs"
    email:
        - vitor@noiselabs.org